version: '3'

services:
  serverless:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ~/.ssh:/root/.ssh:ro,delegated
      - ~/.aws:/root/.aws:ro,delegated
      - node_modules:/workspace/node_modules
      - ..:/workspace:delegated
    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  node_modules:
